# Generated by Django 5.0.4 on 2024-05-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_room_room_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_room',
            name='users_in_room',
            field=models.ManyToManyField(to='chat.users'),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
